version: 1.2.0.{build}
image: Visual Studio 2017

init:
- choco install opencover.portable
- choco install codecov

configuration: Release

before_build:
- nuget restore

build:
  verbosity: minimal
  project: MBRC.sln

test_script:
- OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:".\build\bin\Release\mbrc_core.Test.dll --result:nunitTestResult.xml" -output:".\coverage.xml" "-filter:+[*]* -[*.Test]*"
- codecov -f "coverage.xml"